import React from 'react';
import Card from '../common/Card';
import { FileText, Download, Printer } from 'lucide-react';

const DocumentGenerator = () => {
    return (
        <Card title="Document Generator">
            <div className="flex flex-col h-full">
                <div className="flex-1 bg-white rounded-lg p-6 text-black font-mono text-sm shadow-inner overflow-y-auto max-h-[400px]">
                    <div className="border-b-2 border-black pb-4 mb-4 flex justify-between items-center">
                        <h1 className="text-xl font-bold">INCIDENT REPORT</h1>
                        <span className="text-xs">ID: #SOC-2024-892</span>
                    </div>

                    <div className="space-y-4">
                        <div>
                            <p className="font-bold">Executive Summary:</p>
                            <p>On Dec 09, 2025, a high-severity alert was triggered by Vision One. The system automatically isolated the host (192.168.1.45) following playbook #882.</p>
                        </div>

                        <div>
                            <p className="font-bold">Indicators of Compromise:</p>
                            <ul className="list-disc pl-4">
                                <li>IP: 185.23.12.1 (Malicious)</li>
                                <li>Hash: a1b2c3d4e5...</li>
                            </ul>
                        </div>

                        <div>
                            <p className="font-bold">Actions Taken:</p>
                            <ul className="list-disc pl-4">
                                <li>[Auto] Enrichment via VirusTotal</li>
                                <li>[Auto] Host Isolation</li>
                                <li>[Manual] Analyst Approval (J. Doe)</li>
                            </ul>
                        </div>
                    </div>

                    <div className="mt-8 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
                        Generated by SOC Automation Engine • Confidential
                    </div>
                </div>

                <div className="flex gap-3 mt-4">
                    <button className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg bg-[rgba(255,255,255,0.1)] hover:bg-[rgba(255,255,255,0.2)] transition-colors text-white text-sm font-medium">
                        <Printer size={16} />
                        Print
                    </button>
                    <button className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg bg-[#00f0ff] text-black hover:bg-[#00d0df] transition-colors text-sm font-medium">
                        <Download size={16} />
                        Export PDF
                    </button>
                </div>
            </div>
        </Card>
    );
};

export default DocumentGenerator;
